//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace loly_hub_0._2.webService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/newWebService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="webService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        loly_hub_0._2.webService.CompositeType GetDataUsingDataContract(loly_hub_0._2.webService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<loly_hub_0._2.webService.CompositeType> GetDataUsingDataContractAsync(loly_hub_0._2.webService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loyalty_Program_Otp", ReplyAction="http://tempuri.org/IService1/Loyalty_Program_OtpResponse")]
        string[] Loyalty_Program_Otp(string username, string password, string msisdn, string otp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Loyalty_Program_Otp", ReplyAction="http://tempuri.org/IService1/Loyalty_Program_OtpResponse")]
        System.Threading.Tasks.Task<string[]> Loyalty_Program_OtpAsync(string username, string password, string msisdn, string otp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LP_UpdateUserInfo", ReplyAction="http://tempuri.org/IService1/LP_UpdateUserInfoResponse")]
        int LP_UpdateUserInfo(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LP_UpdateUserInfo", ReplyAction="http://tempuri.org/IService1/LP_UpdateUserInfoResponse")]
        System.Threading.Tasks.Task<int> LP_UpdateUserInfoAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/subtract", ReplyAction="http://tempuri.org/IService1/subtractResponse")]
        int subtract(string username, int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/subtract", ReplyAction="http://tempuri.org/IService1/subtractResponse")]
        System.Threading.Tasks.Task<int> subtractAsync(string username, int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/rollBack", ReplyAction="http://tempuri.org/IService1/rollBackResponse")]
        int rollBack(string username, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/rollBack", ReplyAction="http://tempuri.org/IService1/rollBackResponse")]
        System.Threading.Tasks.Task<int> rollBackAsync(string username, int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : loly_hub_0._2.webService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<loly_hub_0._2.webService.IService1>, loly_hub_0._2.webService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public loly_hub_0._2.webService.CompositeType GetDataUsingDataContract(loly_hub_0._2.webService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<loly_hub_0._2.webService.CompositeType> GetDataUsingDataContractAsync(loly_hub_0._2.webService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string[] Loyalty_Program_Otp(string username, string password, string msisdn, string otp) {
            return base.Channel.Loyalty_Program_Otp(username, password, msisdn, otp);
        }
        
        public System.Threading.Tasks.Task<string[]> Loyalty_Program_OtpAsync(string username, string password, string msisdn, string otp) {
            return base.Channel.Loyalty_Program_OtpAsync(username, password, msisdn, otp);
        }
        
        public int LP_UpdateUserInfo(string username, string password) {
            return base.Channel.LP_UpdateUserInfo(username, password);
        }
        
        public System.Threading.Tasks.Task<int> LP_UpdateUserInfoAsync(string username, string password) {
            return base.Channel.LP_UpdateUserInfoAsync(username, password);
        }
        
        public int subtract(string username, int value) {
            return base.Channel.subtract(username, value);
        }
        
        public System.Threading.Tasks.Task<int> subtractAsync(string username, int value) {
            return base.Channel.subtractAsync(username, value);
        }
        
        public int rollBack(string username, int id) {
            return base.Channel.rollBack(username, id);
        }
        
        public System.Threading.Tasks.Task<int> rollBackAsync(string username, int id) {
            return base.Channel.rollBackAsync(username, id);
        }
    }
}
